slack:
    app-token: SLACK_APP_TOKEN
    bot-token: SLACK_BOT_TOKEN
    welcome-module:
        enabled: false
        channel: SLACK_CHANNEL_ID

breezeway:
    enabled: false
    client-id: BREEZEWAY_CLIENT_ID
    client-secret: BREEZEWAY_CLIENT_SECRET
    url: api.breezeway.io
    company-id: BREEZEWAY_COMPANY_ID